package org.cbom.java;

import org.bouncycastle.crypto.digests.SHA256Digest;
import org.bouncycastle.crypto.digests.SHA512Digest;
import org.bouncycastle.crypto.engines.AESEngine;
import org.bouncycastle.crypto.macs.HMac;
import org.bouncycastle.crypto.prng.EntropySource;
import org.bouncycastle.crypto.prng.EntropySourceProvider;
import org.bouncycastle.crypto.prng.drbg.SP80090DRBG;
import org.bouncycastle.crypto.prng.drbg.CTRSP800DRBG;
import org.bouncycastle.crypto.prng.drbg.HashSP800DRBG;
import org.bouncycastle.crypto.prng.drbg.HMacSP800DRBG;
import org.bouncycastle.crypto.prng.BasicEntropySourceProvider;

import java.security.SecureRandom;

public class DRBGTest {

    public static void main(String[] args) {
        try {
            SecureRandom secureRandom = new SecureRandom();
            EntropySourceProvider entropyProvider = new BasicEntropySourceProvider(secureRandom, true);

            byte[] personalizationString = "TestPersonalization".getBytes();
            byte[] nonce = new byte[16];
            secureRandom.nextBytes(nonce);

            System.out.println("===== DRBG Tests (NIST SP 800-90A Compliant) =====");

            // Hash_DRBG with SHA-256
            System.out.println("\nHash_DRBG (SHA-256):");
            EntropySource hashEntropy = entropyProvider.get(256);
            SP80090DRBG hashDRBG = new HashSP800DRBG(
                    new SHA256Digest(),
                    256,
                    hashEntropy,
                    personalizationString,
                    nonce
            );
            testDRBG(hashDRBG);

            // HMAC_DRBG with SHA-512
            System.out.println("\nHMAC_DRBG (SHA-512):");
            EntropySource hmacEntropy = entropyProvider.get(512);
            SP80090DRBG hmacDRBG = new HMacSP800DRBG(
                    new HMac(new SHA512Digest()),
                    512,
                    hmacEntropy,
                    personalizationString,
                    nonce
            );
            testDRBG(hmacDRBG);

            // CTR_DRBG with AES-256
            System.out.println("\nCTR_DRBG (AES-256):");
            EntropySource ctrEntropy = entropyProvider.get(256);
            SP80090DRBG ctrDRBG = new CTRSP800DRBG(
                    new AESEngine(),
                    256, // AES key size
                    256, // security strength
                    ctrEntropy,
                    personalizationString,
                    nonce
            );
            testDRBG(ctrDRBG);

            System.out.println("\n===== DRBG Testing Complete =====");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static void testDRBG(SP80090DRBG drbg) {
        byte[] output = new byte[64]; // 512-bit output
        int status = drbg.generate(output, null, false);
        if (status < 0) {
            System.out.println("DRBG failed to generate output.");
        } else {
            System.out.println("Generated Bytes: " + bytesToHex(output));
        }
    }

    private static String bytesToHex(byte[] bytes) {
        return Utils.toHexString(bytes);
    }
}
